---
- name: Include OS-specifc variables.
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Ensure steam user exists
  user:
    name: "{{ steamcmd_user }}"

- name: Ensure required packages are installed
  package:
    name: "{{ steamcmd_required_packages }}"
    state: present

- name: Execute OS-specific tasks.
  include_tasks: install-{{ ansible_os_family }}.yml

- name: Ensure steam is initialized by connecting as anonymous
  command: "{{ steamcmd_bin }} +login anonymous +quit"
  become_user: "{{ steamcmd_user }}"
  changed_when: no

- name: Check if .steam directory exists.
  stat:
    path: "/home/{{ steamcmd_user }}/.steam"
  register: __dot_steam

- name: Check if Steam directory exists.
  stat:
    path: "/home/{{ steamcmd_user }}/Steam"
  register: __Steam

- name: Set the steam_home variable.
  set_fact:
    steam_home: "/home/{{ steamcmd_user }}/.steam"
    cacheable: yes
  when: __dot_steam.stat.exists

- name: Set the steam_home variable.
  set_fact:
    steam_home: "/home/{{ steamcmd_user }}/Steam"
    cacheable: yes
  when: __Steam.stat.exists
